# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
  url: '%env(MAILER_URL)%'
  # send all emails to a specific address
  delivery_addresses: ['developpementtest@outlook.fr']
  sender_address: '%env(resolve:MAILER_FROM_ADDRESS)%'